---
title: "Cytometer_import"
output:
  html_document:
    df_print: paged
Author: Maximilian Berthold, Sylwia Sliwinska-Wilczewska, Naaman Oman, Mireille Savoie
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# knitr::opts_chunk$set(fig.path='Figs/')
```

#Below are the parameters for the data import of the Cytometer data.


```{r}
Project <- "PicoBaltic"
DataOut <- file.path("..", "ImportedData", "MDPico")

DataIn <- file.path("..", "MDPico", "CC", fsep = .Platform$file.sep)

FileID <- "ExperimentSummaryData"

#MDPicoGoogle <- "https://docs.google.com/spreadsheets/d/1Lerp5u25kzBtaBbnOYElYqUP59cn68gJpxxayhnGdkw/edit#gid=0"

FileEncode <- "UTF-8" 
Delimiter <- ","

HeaderRows <- 0

#NFlagError <- 0.2  # percentage of N that std error must be less than
```


#Packages needed.

```{r}

library(tidyverse)
library(lubridate)
library(stringr)
library(broom)
library(knitr)
library(OneR)
library(zoo)
library(strucchange)

library(dplyr)
library(magrittr)
library(googledrive)
library(googlesheets4)
library(readxl)
```



Load metadatacatalog
```{r load local metadatacatalog, message = FALSE, warning = FALSE, echo=FALSE}
gs4_deauth()

# imagine this is the URL or ID of a Sheet readable by anyone (with a link)

MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1Lerp5u25kzBtaBbnOYElYqUP59cn68gJpxxayhnGdkw/edit#gid=0") %>%
  #mutate(Date = as.numeric(Date)) %>%
  mutate(Date = ymd_hm(`Date`)) %>%
  separate(Date, into = c("Date_count", "Time_count"), sep = " ", remove = FALSE) %>%
  mutate(Date_count = ymd(`Date_count`)) 
  #mutate(StartExDate = ymd(`StartExDate`)) 
  #mutate(StartExDate = as.numeric(StartExDate))
  #mutate(Date_count = as.numeric(Date_count)) 

  

# %>%
#   
# # drop_na(WL) %>%
# #   mutate(WL = unlist(WL))
# # 
# #as.data.frame(MetaData)
# 
# #MetaData <- MetaData %>%
# MetaData <- MetaData %>%

```

Load Multiculti catalog
```{r load local multiculticatalog, message = FALSE, warning = FALSE, echo=FALSE}
# #implement read with googlesheet name instead of full url

gs4_deauth()

# imagine this is the URL or ID of a Sheet readable by anyone (with a link)
# MultiCulti metadata
Catalog <- read_sheet("https://docs.google.com/spreadsheets/d/1ZXpwR7Gfto-uRzVdXzMpQF4frbrvMLH_IyLqonFZRSw/edit#gid=0") %>%
  # read_sheet has an annoying "feature" to set the type of columns it can't parse to a list.
  # ggplot/dplyr doesn't like working with a dataframe of lists.
  # In this case WL is set to a list since some values are numbers, some are strings, some are blank.
  # To fix this, first drop all rows missing WL, then unlist.
  # Must first drop NA rows since unlist will collapse NULL lists, then the unlisted WL is a shorter length than original WL column, which mutate doesn't like.
  drop_na(WL) %>%
  mutate(WL = unlist(WL))

as.data.frame(Catalog)

Catalog <- Catalog %>%
   mutate(ExpDate = ymd(ExpDate),
          ExpEndDate = ymd_hms(`ExpEndDate`))
```

```{r set colours}
Wavelengths_nm = c(445, 470, 505, 535, 590)
Colours_nm = c("darkblue", "dodgerblue", "darkgreen", "yellowgreen",  "darkorange")


names(Colours_nm) <- Wavelengths_nm
Colours_nm
```

```{r}
MetaDataAll <- MetaData %>%
  left_join(., Catalog, by = c("CultureID" = "ID"))
```



```{r}
CountFiles <- list.files(path = DataIn, pattern = FileID, full.names = TRUE)
CountFiles

#test for duplicate file names
unique(duplicated(CountFiles))
```

```{r data read adds filename and cdate, warning=FALSE, message=FALSE, echo=FALSE}
#design choice 2 file reading functions or add a filetype variable to a single function
#stringsAsFactors =FALSE somewhere? 

read.delim_plus <- function(flnm, file_encode, delimiter, header_rows){read.delim(flnm, fileEncoding = file_encode, sep = delimiter,  skip = header_rows, row.names = NULL) %>% mutate(filename = flnm, cdatetime = ymd_hms(file.info(flnm)$ctime))
}
```

purrr::map to read all files
```{r read MDPico file}
CountTidy <- CountFiles %>%
  map_df(~read.delim_plus(flnm =., file_encode = FileEncode, delimiter = Delimiter, header_rows = HeaderRows))
```




```{r tidy CountTidy}

CountTidyAll <- CountTidy %>% 
  #filter(!grepl("----", DATE)) %>% # remove rows with "----"
  select(-c("Concentration", "Group", "Compound")) %>% # remove superfluous columns
  mutate(filename = str_remove(string = filename, pattern = ".csv")) %>%
  mutate(filename = str_remove(string = filename, pattern = "../MDPico/")) %>%
  # separate(filename, into = c("Device", "Project", "DateTime", "CalOxy",  "CultureID", "Ex_WL", "Exp_Type", "fit"), sep = "([\\/\\/\\_\\_\\_\\_])", remove = FALSE) %>%
  separate(filename, into = c("Method", "ObsDate", "Project", "Initials",  "PlateNr", "IndStud", "Organism", "Count"), sep = "([\\/\\/\\_\\_\\_\\_])", remove = FALSE) %>%
  
  # mutate(DATE = ymd(DATE),
  #         TIME = as.character(TIME)) %>% 
  
  # rename(ObsDate = DATE,
  #        ObsTime = TIME,
  #        FvFm = "Fv.Fm") %>%
  #mutate(cdatetime = as.numeric(cdatetime)) %>%
  # mutate(FvFm = as.numeric(as.character(FvFm)),
  #        nm445 = as.numeric(as.character(Light_1)),
  #        nm590 = as.numeric(as.character(Light_5))) %>%
  mutate(cdatetime = ymd_hms(cdatetime)) %>%
  mutate(ObsDate = ymd_hm(ObsDate)) 
  # rename(StartDateTimeSol = DateTime) %>%
  # drop_na(StartDateTimeSol) %>%
  # mutate(ObsTime = hms(ObsTime)) %>%
  # mutate(ObsDateTime = ymd_hms(paste(ObsDate, ObsTime))) %>%
  # relocate(ObsDateTime, .after = ObsTime) %>%
  # relocate(CultureID, .before = ObsDate) 

# CountTidyAll <- CountTidyAll %>%
#   mutate(across(.cols = c(Cell.Count:Average.Area), .fns = as.numeric)) %>%
  # mutate(ActPAR = Light_1 + Light_2 + Light_3 + Light_4 + Light_5 + Light_6) 
# 
# CountTidyAll[1,]

# 
# CountTidyAll <- CountTidyAll %>%
#   group_by(T.Id) 



```


```{r}
CountMetaAll <- CountTidyAll %>%
  mutate(PlateNr = as.double(PlateNr)) %>%
  # mutate(Date = as.numeric(Date)) %>%
  # mutate(Date = ymd_hms(`Date`))
  left_join(., MetaDataAll, by = c("Well.Name" = "WellNumber", "PlateNr" = "PlateNumber"))


```



```{r}
CountMetaAll <- CountMetaAll %>%
  mutate(culture_inocul_L = as.double(culture_inocul_L)) %>%
  mutate(CapAreaPercentage = as.double(CapAreaPercentage)) %>%

  mutate(cellsml = (`Cell.Count` * (0.001/culture_inocul_L)) /(CapAreaPercentage/100)) %>%
  # mutate(cellsml = `cellsmlwithoutpercentage`/(CapAreaPercentage/100))
group_by(Date, CultureID) %>%

summarize(Well.Name, Cell.Count, filename, Method, ObsDate, PlateNr, cdatetime, PlateID, CultureID, Date, Date_count, Time_count, media_inocul_L, culture_inocul_L, MolDev_FileName, CapAreaPercentage, Run, Strain, InnocDate, ExpDate, Par_ue, Photoperiod, `Calculated_µmolPhotons_m-2d-1`, Tube, O2, WL, LightShape, ExpEndDate, cellsml, meancellsml = mean(cellsml), secellsml = sd(cellsml)/n()^(1/2), sdcellsml = sd(cellsml)) %>%

ungroup() %>%
  
  
group_by(CultureID) %>%
  arrange(Date_count) %>%
  mutate(E_days = as.numeric((Date_count - ExpDate[1]))) %>%
ungroup()
  


# Designations:
# Date <- day on which the test sample was taken from MultiCulti - format ymd_hm
# Date_count <- day on which the test sample was taken from MultiCulti - format ymd
# Time_count <- time on which the test sample was taken from MultiCulti - format hm
# ObsDate <- day the sample on the MDPico was tested
# cdatetime <- time the dMDPico finished analyzing the sample
# InnocDate <- day indicating the innoculation of the multiculti experiment
# ExpDate <- day indicating the start of the multiculti experiment 

```

WW Photoperiod Plot
```{r fig.height = 6, fig.width = 8, echo = FALSE}
# Par_ue.labs <- c("30 µE", "90 µE", "180 µE", "300 µE", "900 µE")
# names(Par_ue.labs) <- c("30", "90", "180", "300", "900")

CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Strain == "BA48R"|
         Strain == "BA127R"|
         Strain == "BA56G"|
         Strain == "BA77G") %>%
  filter(Run != "64",
         Run != "67") %>%
  filter(WL == "WW") %>%
  filter(Par_ue != "60",
         Par_ue != "600") %>% 
  ggplot() +
  geom_point(aes(x = E_days, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = E_days, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Time (d)") +
  #labs(y = "Number of cells (N" ~mL^-1~")", x = "Time (d)") +
  ggh4x::facet_nested(rows = vars(Par_ue), cols = vars(Strain, Photoperiod), labeller = labeller(Ex_WL = label_both, strain = label_value, WL = label_both, Photoperiod = label_value, Par_ue = label_both)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot


CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Strain == "BA48R"|
         Strain == "BA127R"|
         Strain == "BA56G"|
         Strain == "BA77G") %>%
  filter(Run != "64",
         Run != "67") %>%
  filter(WL == "WW") %>%
  filter(Par_ue != "60",
         Par_ue != "600") %>% 
  filter (E_days == 3|
          E_days == 6|
          E_days == 7) %>%
  ggplot() +
  geom_point(aes(x = Par_ue, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = Par_ue, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Growth Light (µmol photons" ~m^-2 ~s^-1~")") +
  #labs(y = "Number of cells (N" ~mL^-1~")", x = "Time (d)") +
  ggh4x::facet_nested(rows = vars(Photoperiod), cols = vars(Strain), labeller = labeller(Ex_WL = label_both, strain = label_value, Par_ue = label_both, WL = label_both, Photoperiod = label_both)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot


CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Strain == "BA48R"|
         Strain == "BA127R"|
         Strain == "BA56G"|
         Strain == "BA77G") %>%
  filter(Run != "64",
         Run != "67") %>%
  filter(WL == "WW") %>%
  filter(Par_ue != "60",
         Par_ue != "600") %>% 
  filter (E_days == 14) %>%
  ggplot() +
  geom_point(aes(x = Par_ue, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = Par_ue, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Growth Light (µmol photons" ~m^-2 ~s^-1~")") +
  #labs(y = "Number of cells (N" ~mL^-1~")", x = "Time (d)") +
  ggh4x::facet_nested(rows = vars(Photoperiod), cols = vars(Strain), labeller = labeller(Ex_WL = label_both, strain = label_value, Par_ue = label_both, WL = label_both, Photoperiod = label_both)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot

```



CCA Plot
```{r fig.height = 6, fig.width = 8, echo = FALSE}
# Par_ue.labs <- c("60 µE", "300 µE", "60 µE", "30 µE")
# names(Par_ue.labs) <- c("60", "300", "60", "30")
CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Run == "56"|
         Run == "59"|
         Run == "63"|
         Run == "68"|
         Run == "70") %>%
  # filter(Well.Name != "D3"|
  #       PlateID != "SySl_104") %>% 
  # filter(Well.Name != "D5"|
  #       PlateID != "SySl_126") %>% 
  ggplot() +
  geom_point(aes(x = E_days, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = E_days, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Time (d)") +
  #labs(y = "Number of cells (N" ~mL^-1~")") +
  #scale_x_continuous(breaks=seq(8, 24, by = 4)) +
  #coord_cartesian(xlim = c (6, 26)) +
  ggh4x::facet_nested(rows = vars(Par_ue),cols = vars(Strain, WL), labeller = labeller(Ex_WL = label_both, strain = label_value, WL = label_both, Photoperiod = label_both, Par_ue = label_both)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot



CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Run == "68") %>%
  ggplot() +
  geom_point(aes(x = Par_ue, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = Par_ue, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Growth Light (µmol photons" ~m^-2 ~s^-1~")") +
  #labs(y = "Number of cells (N" ~mL^-1~")") +
  scale_y_continuous(breaks=seq(0, 25, by = 5)) +
  coord_cartesian(ylim = c (0, 25)) +
  ggh4x::facet_nested(rows = vars(Photoperiod), cols = vars(Strain, WL), labeller = labeller(Ex_WL = label_both, strain = label_value, Par_ue = label_both, WL = label_both, Photoperiod = label_both)) +
  theme_bw()
CellPlot



```

```{r}
# CellPlot2 %>%
#   plotly::ggplotly()
```



Color Light Plot
```{r fig.height = 6, fig.width = 8, echo = FALSE}
O2.labs <- c("Oxygen level: high", "Oxygen level: low", "Oxygen level: high")
names(O2.labs) <- c("21", "0", "21")
CellPlot <- CountMetaAll %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Run == "57"|
         Run == "61"|
         Run == "76") %>%
  filter(WL != "WW") %>% 
  ggplot() +
  geom_point(aes(x = E_days, y = meancellsml107, label = CultureID)) +
  geom_errorbar(aes(x = E_days, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Time (d)") +
  #labs(y = "Number of cells (N" ~mL^-1~")", x = "Time (d)") +
  #scale_x_continuous(breaks=seq(8, 24, by = 4)) +
  #coord_cartesian(xlim = c (6, 26)) +
  ggh4x::facet_nested(rows = vars(WL), cols = vars(Strain, O2), labeller = labeller(Ex_WL = label_both, strain = label_value, Par_ue = label_both, WL = label_both, Photoperiod = label_both, O2 = O2.labs)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot



O2.labs <- c("Oxygen level: high", "Oxygen level: low", "Oxygen level: high")
names(O2.labs) <- c("21", "0", "21")
CellPlot <- CountMetaAll %>%
  mutate(WLNum = if_else(WL == "WW", 750, as.numeric(WL))) %>%
  mutate(meancellsml107 = meancellsml/10000000) %>%
  mutate(sdcellsml107 = sdcellsml/10000000) %>%
  filter(Run == "57"|
         Run == "61"|
         Run == "76") %>%
  filter(WL != "WW") %>% 
  filter(E_days == 7|
         E_days == 8) %>% 
  ggplot() +
  geom_point(aes(x = WLNum, y = meancellsml107, label = CultureID)) +
  geom_line(aes(x = WLNum, y = meancellsml107, label = CultureID), color = 'black') +
  geom_errorbar(aes(x = WLNum, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells (N" ~10^7 ~mL^-1~")", x = "Wavelength (nm)") +
  #labs(y = "Number of cells (N" ~mL^-1~")", x = "Time (d)") +
  #scale_x_continuous(breaks=seq(8, 24, by = 4)) +
  #coord_cartesian(xlim = c (6, 26)) +
  ggh4x::facet_nested(rows = vars(Photoperiod), cols = vars(Strain, O2), labeller = labeller(Ex_WL = label_both, strain = label_value, Par_ue = label_both, WL = label_both, Photoperiod = label_both, O2 = O2.labs)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
CellPlot

```
```{r}
colnames(CountMetaAll)

CountMetaAll<-CountMetaAll %>% 
  rename(PhotonDose="Calculated_µmolPhotons_m-2d-1") %>% 
  rename(CellCount=Cell.Count) %>% 
  rename(WellName=Well.Name) %>% 
  rename(DateCollect=Date_count) %>% 
  rename(TimeCollect=Time_count) %>% 
  select(-c(secellsml, cdatetime,filename, Date))


```


```{r save MDPico data}

saveRDS(CountMetaAll, file.path(DataOut, paste(Project, "MDPico.Rds", sep = "_"), fsep = .Platform$file.sep))

```





```{r}
Project <- "PicoBaltic"
DataOut <- file.path("..", "ImportedData", "MDPico")
DataIn <- file.path("..", "MDPico", "Correlation", fsep = .Platform$file.sep)

FileID <- "ExperimentSummaryData"
FileEncode <- "UTF-8" 
Delimiter <- ","
HeaderRows <- 0

```


Load metadatacatalog
```{r load local metadatacatalog, message = FALSE, warning = FALSE, echo=FALSE}
gs4_deauth()

# imagine this is the URL or ID of a Sheet readable by anyone (with a link)

MetaDataCorrelation <- read_sheet("https://docs.google.com/spreadsheets/d/1xDZ5eiCFgqJ-AgO7jhCSKS7oyO39KpwjZm0UpdP2p2c/edit#gid=0") %>%
  #mutate(Date = as.numeric(Date)) %>%
  mutate(Date = ymd_hm(`Date`)) %>%
  separate(Date, into = c("Date_count", "Time_count"), sep = " ", remove = FALSE) %>%
  mutate(Date_count = ymd(`Date_count`)) 
  #mutate(StartExDate = ymd(`StartExDate`)) 
  #mutate(StartExDate = as.numeric(StartExDate))
  #mutate(Date_count = as.numeric(Date_count)) 

```



```{r}
CountFiles <- list.files(path = DataIn, pattern = FileID, full.names = TRUE)
CountFiles

#test for duplicate file names
unique(duplicated(CountFiles))
```

```{r data read adds filename and cdate, warning=FALSE, message=FALSE, echo=FALSE}
#design choice 2 file reading functions or add a filetype variable to a single function
#stringsAsFactors =FALSE somewhere? 

read.delim_plus <- function(flnm, file_encode, delimiter, header_rows){read.delim(flnm, fileEncoding = file_encode, sep = delimiter,  skip = header_rows, row.names = NULL) %>% mutate(filename = flnm, cdatetime = ymd_hms(file.info(flnm)$ctime))
}
```

purrr::map to read all files
```{r read MDPico file}
CountTidy <- CountFiles %>%
  map_df(~read.delim_plus(flnm =., file_encode = FileEncode, delimiter = Delimiter, header_rows = HeaderRows))
```




```{r tidy CountTidy}

CountTidyAll <- CountTidy %>% 
  #filter(!grepl("----", DATE)) %>% # remove rows with "----"
  select(-c("Concentration", "Group", "Compound")) %>% # remove superfluous columns
  mutate(filename = str_remove(string = filename, pattern = ".csv")) %>%
  mutate(filename = str_remove(string = filename, pattern = "../MDPico/")) %>%
  # separate(filename, into = c("Device", "Project", "DateTime", "CalOxy",  "CultureID", "Ex_WL", "Exp_Type", "fit"), sep = "([\\/\\/\\_\\_\\_\\_])", remove = FALSE) %>%
  separate(filename, into = c("Method", "ObsDate", "Project", "Initials",  "PlateNr", "Correlation", "Methods", "Organism"), sep = "([\\/\\/\\_\\_\\_\\_])", remove = FALSE) %>%
  
  # mutate(DATE = ymd(DATE),
  #         TIME = as.character(TIME)) %>% 
  
  # rename(ObsDate = DATE,
  #        ObsTime = TIME,
  #        FvFm = "Fv.Fm") %>%
  #mutate(cdatetime = as.numeric(cdatetime)) %>%
  # mutate(FvFm = as.numeric(as.character(FvFm)),
  #        nm445 = as.numeric(as.character(Light_1)),
  #        nm590 = as.numeric(as.character(Light_5))) %>%
  mutate(cdatetime = ymd_hms(cdatetime)) %>%
  mutate(ObsDate = ymd_hm(ObsDate)) 
  # rename(StartDateTimeSol = DateTime) %>%
  # drop_na(StartDateTimeSol) %>%



```


```{r}
CountMetaAllCorrelation <- CountTidyAll %>%
  mutate(PlateNr = as.double(PlateNr)) %>%
  # mutate(Date = as.numeric(Date)) %>%
  # mutate(Date = ymd_hms(`Date`))
  left_join(., MetaDataCorrelation, by = c("Well.Name" = "WellNumber", "PlateNr" = "PlateNumber"))


```



```{r}
colnames(CountMetaAllCorrelation)

CountMetaAllCorrelation <- CountMetaAllCorrelation %>%
  mutate(culture_inocul_L = as.double(culture_inocul_L)) %>%
  mutate(CapAreaPercentage = as.double(CapAreaPercentage)) %>%

  mutate(cellsml = (`Cell.Count` * (0.001/culture_inocul_L)) /(CapAreaPercentage/100)) %>%
  # mutate(cellsml = `cellsmlwithoutpercentage`/(CapAreaPercentage/100))
group_by(Date, Strain, Dilution) %>%

summarize(Well.Name, Cell.Count, filename, Method, ObsDate, PlateNr, PlateID, Strain,Dilution,Date, Date_count, Time_count, media_inocul_L, culture_inocul_L, CapAreaPercentage, TotArea_mm2, CapArea_mm2, cellsml, meancellsml = mean(cellsml), secellsml = sd(cellsml)/n()^(1/2), sdcellsml = sd(cellsml)) %>%


ungroup() 
  


# Designations:
# Date <- day on which the test sample was taken from MultiCulti - format ymd_hm
# Date_count <- day on which the test sample was taken from MultiCulti - format ymd
# Time_count <- time on which the test sample was taken from MultiCulti - format hm
# ObsDate <- day the sample on the MDPico was tested
# cdatetime <- time the dMDPico finished analyzing the sample
# InnocDate <- day indicating the innoculation of the multiculti experiment
# ExpDate <- day indicating the start of the multiculti experiment 

```


Plot
```{r fig.height = 6, fig.width = 8, echo = FALSE}
# Par_ue.labs <- c("60 µE", "300 µE", "60 µE", "30 µE")
# names(Par_ue.labs) <- c("60", "300", "60", "30")
Plot <- CountMetaAllCorrelation %>%
  # mutate(meancellsml107 = meancellsml/10000000) %>%
  # mutate(sdcellsml107 = sdcellsml/10000000) %>%


  ggplot() +
  geom_point(aes(x = Dilution, y = meancellsml)) +
  # geom_errorbar(aes(x = E_days, ymin = meancellsml107-sdcellsml107, ymax = meancellsml107+sdcellsml107)) +
  # scale_color_manual(values = Colours_nm) +
  guides(colour = FALSE) +
  labs(y = "Number of cells/mL", x = "Time (d)") +
  #labs(y = "Number of cells (N" ~mL^-1~")") +
  #scale_x_continuous(breaks=seq(8, 24, by = 4)) +
  #coord_cartesian(xlim = c (6, 26)) +
  ggh4x::facet_nested(cols = vars(Strain), labeller = labeller(Ex_WL = label_both, strain = label_value, WL = label_both, Photoperiod = label_both, Par_ue = label_both)) +
  #scale_x_continuous(limits = c(0,160)) +
  theme_bw()
Plot


```

```{r}
colnames(CountMetaAllCorrelation)

CountMetaAllCorrelation<-CountMetaAllCorrelation %>%
  rename(CellCount=Cell.Count) %>%
  rename(WellName=Well.Name) %>%
  rename(MolDev_FileName=filename) %>% 
  rename(DateCollect=Date_count) %>% 
  rename(TimeCollect=Time_count) %>% 
  select(-c(secellsml, TotArea_mm2, CapArea_mm2, Date))


```

```{r save MDPico data}

saveRDS(CountMetaAllCorrelation, file.path(DataOut, paste(Project, "MDPicoCorrelation.Rds", sep = "_"), fsep = .Platform$file.sep))

```








