---
title: "MCDielLight"
author:
- Douglas A. Campbell
- Sylwia Wilczewska-Wilinska
date: "`r format(Sys.Date())`"
bibliography: Prochlorococcus_O2_NPQ.bib
csl: plos-one.csl
editor_options: 
  markdown: 
    wrap: 72
---
# This Rmd loads previously imported,  tidied data from the PSI MC and generates estimates of hourly and diel cumulative photon dose to cultures.

# Set Options

## Set figure caption font size

```{css, echo=FALSE}
p.caption {
  font-size: 18px;
}
```

## Set Chunk Options

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```

```{r libraries}
library(tidyverse)
library(zoo)
```

```{r colour setting}
# Bin4_nm <- c(440, 510, 590, 660)
# Bin4Colours <- c(w_length2rgb(440), w_length2rgb(510), w_length2rgb(590), w_length2rgb(660))
# names(Bin4Colours) <- Bin4_nm
```

## Read Data
```{r data files}
MCFiles <- list.files(path = file.path("..", "Data", "ImportedData", "ImportedMCData"), full.names = TRUE)
MCFiles
```

```{r read data}

MCData <- readRDS(file = MCFiles[1]) |>
  ungroup() |>
  mutate(deltaOD = OD680 - OD720)

  colnames(MCData)
```

```{r par_time_plot}
MCData |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(Tube == 4) |>
  # filter(time >= 48,
  #        time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```

#https://stackoverflow.com/questions/76603287/calculate-linear-regression-slope-with-moving-window
```{r growth rates}

# slope <- function(x) coef(lm(x[, 2] ~ x[, 1]))[[2]]
slope <- function(x) cov(x[, 1], x[, 2]) / var(x[, 1])

#FitWindow_h <- 2
#maybe issues still with changes in light level that do not align with growth measurement points

#maybe should estimate growth rates, then use 'summarize' to do sum of actinic photon dose for each hour?

ODinterval<-5

MCDataHour <- MCData |>
  group_by(Filename, Tube, Day) |>
  filter(deltaOD > 0) |>
  mutate(Actinic_photonsm2h = zoo::rollsum(Actinic_par * 5 * 60, k = 12, fill = NA, align = "right")) |> #PAR per h
  mutate(mu_deltaODwindow = rollapply(cbind(time, log(deltaOD)), 12, slope, by.column=FALSE, fill=NA)) |> #slope
  mutate(mu_Averh = zoo::rollmean(mu_deltaODwindow, k = 12, fill = NA, align = "right")) |> #average of first 12 row
  ungroup() |>
  filter(time - round(time) == 0)

MCDataHour |>
  # filter(time >= 48,
  #        time <= 72) |>
  filter(time < 100) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  # filter(time >= 48,
  #        time <= 72) |>
  filter(time < 100) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_Averh, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```


```{r hourly plots exploration}
#temporary
#use case_when to remove 'dark' periods?
#bad to filter and only then estimate growth rates; better to do across 1 h window

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_photonsm2h, colour = WL)) +
  geom_point(aes(x = time, y = mu_Averh * 10000)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = Actinic_photonsm2h, y = mu_Averh, colour = ToD)) +
  geom_line(aes(x = Actinic_photonsm2h, mu_Averh, colour = ToD)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_Averh, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_Averh, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  filter(Tube == 4) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_Averh, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()


MCDataHour |>
   filter(time <= 100) |>
  #filter(Actinic_par > 1) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_Averh, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_Averh, colour = Actinic_photonsm2h)) +
  geom_smooth(aes(x = ToD, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

```


