---
title: "MCDielLight"
author:
- Douglas A. Campbell
- Sylwia Wilczewska-Wilinska
date: "`r format(Sys.Date())`"
bibliography: Prochlorococcus_O2_NPQ.bib
csl: plos-one.csl
editor_options: 
  markdown: 
    wrap: 72
---
# This Rmd loads previously imported,  tidied data from the PSI MC and generates estimates of hourly and diel cumulative photon dose to cultures.

# Set Options

## Set figure caption font size

```{css, echo=FALSE}
p.caption {
  font-size: 18px;
}
```

## Set Chunk Options

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```

```{r libraries}
library(tidyverse)
library(zoo)

library(gcookbook)  # Load gcookbook for the uspopage data set
library(viridis)  # Load viridis for the viridis palette
library("RColorBrewer")
```

```{r colour setting}
# Bin4_nm <- c(440, 510, 590, 660)
# Bin4Colours <- c(w_length2rgb(440), w_length2rgb(510), w_length2rgb(590), w_length2rgb(660))
# names(Bin4Colours) <- Bin4_nm
```

## Read Data
```{r read data}
MCFiles <- list.files(path = file.path("..", "Data", "ImportedData", "ImportedMCData"), full.names = TRUE)
MCFiles

MCData <- readRDS(file = MCFiles[3]) |>
  ungroup() |>
  mutate(deltaOD = OD680 - OD720)

  colnames(MCData)
```

```{r par_time_plot}
MCData |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(Tube == 2) |>
  # filter(time >= 48,
  #        time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```

#https://stackoverflow.com/questions/76603287/calculate-linear-regression-slope-with-moving-window
```{r growth rates}

# slope <- function(x) coef(lm(x[, 2] ~ x[, 1]))[[2]]
slope <- function(x) cov(x[, 1], x[, 2]) / var(x[, 1])

#FitWindow_h <- 2
#maybe issues still with changes in light level that do not align with growth measurement points

#maybe should estimate growth rates, then use 'summarize' to do sum of actinic photon dose for each hour?

# k=12 ->b/c of photoperiod 12->12h of light per day?
MCDataHour <- MCData |>
  group_by(Filename, Tube, Day) |>
  filter(deltaOD > 0) |>
  mutate(Actinic_photonsm2h = zoo::rollsum(Actinic_par, k = 12, fill = NA, align = "right") * 5 * 60) |> 
  mutate(mu_deltaODwindow = rollapply(cbind(time, log(deltaOD)), 24, slope, by.column=FALSE, fill=NA)) |>
  #mutate(mu_Averh = zoo::rollmean(mu_deltaODwindow, k = 12, fill = NA, align = "right")) |>
  ungroup() |>
  filter(time - round(time) == 0)

MCDataHour |>
  # filter(time >= 48,
  #        time <= 72) |>
  filter(time < 100) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  filter(Tube == 5) %>% 
  filter(time >= 48,
         time <= 72) |>
  #filter(time < 24) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```


```{r hourly plots exploration}
#temporary
#use case_when to remove 'dark' periods?
#bad to filter and only then estimate growth rates; better to do across 1 h window

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_photonsm2h, colour = WL)) +
  geom_point(aes(x = time, y = mu_deltaODwindow * 10000)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = Actinic_photonsm2h, y = mu_deltaODwindow, colour = ToD)) +
  geom_line(aes(x = Actinic_photonsm2h, y = mu_deltaODwindow, colour = ToD)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  filter(Tube == 2) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()


MCDataHour |>
   filter(time <= 100) |>
  #filter(Actinic_par > 1) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_smooth(aes(x = ToD, y = mu_deltaODwindow)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()



myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(100, 1000000))

MCDataHour |>
  filter(Tube == 5) %>% 
   filter(time <= 250) |>
     filter(time >= 48) |>
  #filter(Actinic_par > 1) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  sc +
  #scale_fill_viridis(discrete = TRUE) +
  #scale_fill_brewer() +
  #geom_smooth(aes(x = time, y = mu_deltaODwindow)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

```




https://www.geeksforgeeks.org/support-vector-regression-svr-using-linear-and-non-linear-kernels-in-scikit-learn/

https://minimatech.org/non-linear-regression-with-r/
```{r}
MCDataHourTest <-MCDataHour %>% 
  filter(Day!=0) %>% 
  mutate(time_whzero=time-12) %>% 
  select(c(time, time_whzero, Day, mu_deltaODwindow, Actinic_photonsm2h, Tube)) %>% 
  filter(Tube == 5) %>% 
  filter(time_whzero >= 24) %>% 
   # filter(time <= 240) %>% 
  drop_na(mu_deltaODwindow)
  
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(100, 1000000))

MCDataHourTest |>
  ggplot() +
  geom_point(aes(x = time_whzero, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = time_whzero, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  sc +
    geom_vline(aes(xintercept = 1 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 2 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 3 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 4 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 5 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 6 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 7 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 8 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 9 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 10 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 11 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 12 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 13 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 14 * 24), linetype = "dashed") + 
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```


# Support Vector regression
```{r}
svr_model <- svm(mu_deltaODwindow ~ time_whzero, data = MCDataHourTest, kernel = 'radial',
                 cost = 24, gamma = 100)
resid_svr <- MCDataHourTest$mu_deltaODwindow - predict(svr_model)
sqrt(mean(resid_svr ^ 2))
```

```{r}
## test residuals
test_resid_svr <- MCDataHourTest$mu_deltaODwindow - predict(svr_model, MCDataHourTest)
## test RMSE
sqrt(mean(test_resid_svr ^ 2))
## R Squared
cor(MCDataHourTest$mu_deltaODwindow, predict(svr_model, MCDataHourTest)) ^ 2

MCDataHourTest$svr_pred <- predict(svr_model, MCDataHourTest)
```

```{r}
ggplot(MCDataHourTest, aes(x = time_whzero, y = mu_deltaODwindow)) + 
  geom_point(alpha = 0.3) + 
  geom_line(aes(y = svr_pred, color = 'SVR_radial'), size = 1.3) +
  scale_colour_manual(name="MODELS", values=c(GAM = "#FF9999", SVR_radial = "#0072B2")) +
  theme(legend.position = c(0.8, 0.8)) +
  theme(legend.background=element_rect(fill="white", colour="black"))
```

```{r}

MCDataHourTest %>% 
  ggplot() +
  geom_point(aes(x = time_whzero, y = mu_deltaODwindow), alpha = 0.4) +
  geom_line(aes(x = time_whzero, y = svr_pred, color = 'SVR_radial'), size = 1.3) +
  geom_line(aes(x = time_whzero, y = mu_deltaODwindow)) +
    geom_vline(aes(xintercept = 1 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 2 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 3 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 4 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 5 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 6 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 7 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 8 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 9 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 10 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 11 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 12 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 13 * 24), linetype = "dashed") + 
    geom_vline(aes(xintercept = 14 * 24), linetype = "dashed") + 
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```


