---
title: "MCDielLight"
author:
- Douglas A. Campbell
- Sylwia Wilczewska-Wilinska
date: "`r format(Sys.Date())`"
bibliography: Prochlorococcus_O2_NPQ.bib
csl: plos-one.csl
editor_options: 
  markdown: 
    wrap: 72
---
# This Rmd loads previously imported,  tidied data from the PSI MC and generates estimates of hourly and diel cumulative photon dose to cultures.

# Set Options

## Set figure caption font size

```{css, echo=FALSE}
p.caption {
  font-size: 18px;
}
```

## Set Chunk Options

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```

```{r libraries}
library(tidyverse)
library(zoo)

library(gcookbook)  # Load gcookbook for the uspopage data set
library(viridis)  # Load viridis for the viridis palette
library("RColorBrewer")
```

```{r colour setting}
# Bin4_nm <- c(440, 510, 590, 660)
# Bin4Colours <- c(w_length2rgb(440), w_length2rgb(510), w_length2rgb(590), w_length2rgb(660))
# names(Bin4Colours) <- Bin4_nm
```

## Read Data
```{r read data}
MCFiles <- list.files(path = file.path("..", "Data", "ImportedData", "ImportedMCData"), full.names = TRUE)
MCFiles

MCData <- readRDS(file = MCFiles[3]) |>
  ungroup() |>
  mutate(deltaOD = OD680 - OD720)

  colnames(MCData)
```

```{r par_time_plot}
MCData |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(time >= 48,
         time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCData |>
  filter(Tube == 2) |>
  # filter(time >= 48,
  #        time <= 72) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_par)) +
  geom_point(aes(x = time, y = 1000 * deltaOD, colour = WL)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```

#https://stackoverflow.com/questions/76603287/calculate-linear-regression-slope-with-moving-window
```{r growth rates}

# slope <- function(x) coef(lm(x[, 2] ~ x[, 1]))[[2]]
slope <- function(x) cov(x[, 1], x[, 2]) / var(x[, 1])

#FitWindow_h <- 2
#maybe issues still with changes in light level that do not align with growth measurement points

#maybe should estimate growth rates, then use 'summarize' to do sum of actinic photon dose for each hour?

# k=12 ->b/c of photoperiod 12->12h of light per day?
MCDataHour <- MCData |>
  group_by(Filename, Tube, Day) |>
  filter(deltaOD > 0) |>
  mutate(Actinic_photonsm2h = zoo::rollsum(Actinic_par, k = 12, fill = NA, align = "right") * 5 * 60) |> 
  mutate(mu_deltaODwindow = rollapply(cbind(time, log(deltaOD)), 24, slope, by.column=FALSE, fill=NA)) |>
  #mutate(mu_Averh = zoo::rollmean(mu_deltaODwindow, k = 12, fill = NA, align = "right")) |>
  ungroup() |>
  filter(time - round(time) == 0)

MCDataHour |>
  # filter(time >= 48,
  #        time <= 72) |>
  filter(time < 100) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  filter(Tube == 5) %>% 
  filter(time >= 48,
         time <= 72) |>
  #filter(time < 24) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_point(aes(x = time, y = deltaOD), colour = "green") +
  #geom_point(aes(x = time, y = mu_Averh)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```


```{r hourly plots exploration}
#temporary
#use case_when to remove 'dark' periods?
#bad to filter and only then estimate growth rates; better to do across 1 h window

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = time, y = Actinic_photonsm2h, colour = WL)) +
  geom_point(aes(x = time, y = mu_deltaODwindow * 10000)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = Actinic_photonsm2h, y = mu_deltaODwindow, colour = ToD)) +
  geom_line(aes(x = Actinic_photonsm2h, y = mu_deltaODwindow, colour = ToD)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
   filter(time <= 100) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

MCDataHour |>
  filter(Tube == 2) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()


MCDataHour |>
   filter(time <= 100) |>
  #filter(Actinic_par > 1) |>
  ggplot() +
  geom_point(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = ToD, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_smooth(aes(x = ToD, y = mu_deltaODwindow)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()



myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(100, 1000000))

MCDataHour |>
  filter(Tube == 5) %>% 
   filter(time <= 250) |>
     filter(time >= 48) |>
  #filter(Actinic_par > 1) |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  sc +
  #scale_fill_viridis(discrete = TRUE) +
  #scale_fill_brewer() +
  #geom_smooth(aes(x = time, y = mu_deltaODwindow)) +
  facet_grid(cols = vars(Tube)) +
  theme_bw()

```


https://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/src/timeseries.html
https://www.simplilearn.com/tutorials/data-science-tutorial/time-series-forecasting-in-r

http://r-statistics.co/Time-Series-Analysis-With-R.html


Time Series Analysis
```{r}
#install.packages('forecast')

library(forecast)

data("AirPassengers")

class(AirPassengers)
start(AirPassengers)
sum(is.na(AirPassengers))
summary(AirPassengers)
plot(AirPassengers)


tsdata <- ts(AirPassengers, frequency = 12) #12 years
ddata <- decompose(tsdata, "multiplicative")
plot(ddata)


#Plot the Different Components Individually
plot(ddata$trend)
plot(ddata$seasonal)
plot(ddata$random)


#Build the ARIMA Model Using auto.arima() Function
mymodel <- auto.arima(AirPassengers)
mymodel
```


```{r}
kings <- scan("http://robjhyndman.com/tsdldata/misc/kings.dat",skip=3)
kings

kingstimeseries <- ts(kings)
kingstimeseries
plot.ts(kingstimeseries)
```


Decomposing Time Series
```{r}
library("TTR")

kingstimeseriesSMA3 <- SMA(kingstimeseries,n=3)
plot.ts(kingstimeseriesSMA3)

kingstimeseriescomponents <- decompose(kingstimeseries)
```

https://www.r-bloggers.com/2018/05/regression-modeling-for-time-series/
```{r}
library(gtrendsR)
trends <- gtrends(c("frühling", "spring"), geo = c("DE"))

library(tidyverse)
library(forecast)
library(ggseas)  # install from https://github.com/ellisp/ggseas
 
# turn dataframe into timeseries
create_ts <- function(df, kw){
  df %>% 
    pluck("interest_over_time") %>% 
    filter(date    >= as.Date("2014-01-01"),
           keyword == kw) %>% 
    with(ts(hits, start = c(2014, 1), frequency = 52))
}
fruehling  <- create_ts(trends, "frühling")
spring     <- create_ts(trends, "spring")
# compare decomposition for both time series
cbind(fruehling, spring) %>% 
  ggseas::tsdf() %>% 
  gather("series", "hits", -x) %>% 
  ggseas::ggsdc(aes(x, hits, colour = series), method = "decompose") +
  geom_line() +
  labs(x = "time", y ="hits", title = "Decomposition of Search Traffic")
```
https://minimatech.org/non-linear-regression-with-r/
```{r}
set.seed(13)
x <- rnorm(1000)
noise <- rnorm(1000, sd = 1.5)
y <- 4 * sin(3 * x) + cos(0.8 * x) - 1.5 * (x ^ 2 ) + noise
select <- runif(1000)
d <- data.frame(x = x, y = y)
training <- d[select > 0.1, ]
test <-d[select <= 0.1, ]

ggplot(training, aes(x = x, y = y)) + geom_point(alpha = 0.4) 
  #geom_smooth(se = FALSE, method = 'lm', col = 'black')
```

#Fitting a GAM model
```{r}
library(mgcv)
gam_model <- gam(y ~ s(x), data = training)
gam_model$converged
resid_gam <- training$y - predict(gam_model)
## RMSE
sqrt(mean(resid_gam ^ 2))
```

# Support Vector regression
```{r}
library(e1071)
tuned <- tune.svm(y ~ x, training, kernel = 'radial',
                  gamma = c(seq(0.1, 1, 0.1), 10^(-6:-1)),
                  cost = 10^(-3:1))
tuned

#cost = 10 and gamma = 0.5. these are the best parameters to use with a radial svm kernel in this data.
svr_model <- svm(y ~ x, data = training, kernel = 'radial',
                 cost = 10, gamma = 0.5)
resid_svr <- training$y - predict(svr_model)
sqrt(mean(resid_svr ^ 2))
```


```{r}
## test residuals
test_resid_svr <- test$y - predict(svr_model, test)
test_resid_gam <- test$y - predict(gam_model, test)
## test RMSE
sqrt(mean(test_resid_svr ^ 2))

sqrt(mean(test_resid_gam ^ 2))

## R Squared
cor(test$y, predict(gam_model, test)) ^ 2
cor(test$y, predict(svr_model, test)) ^ 2

```

```{r}
training$svr_pred <- predict(svr_model, training)
training$gam_pred <- predict(gam_model, training)

ggplot(training, aes(x = x, y = y)) + 
  geom_point(alpha = 0.3) + 
  geom_line(aes(y = gam_pred, 
            color = 'GAM'), size = 1.3) +
  geom_line(aes(y = svr_pred,
            color = 'SVR_radial'), size = 1.3) +
  scale_colour_manual(
    name="MODELS", 
    values=c(GAM = "#FF9999", SVR_radial = "#0072B2")) +
  theme(legend.position = c(0.8, 0.8)) +
  theme(legend.background=element_rect(fill="white", colour="black"))
```

```{r}

training$gam_pred <- predict(gam_model, training)

ggplot(training, aes(x = x, y = y)) + 
  geom_point(alpha = 0.3) + 
  geom_line(aes(y = gam_pred, 
            color = 'GAM'), size = 1.3) +
  scale_colour_manual(
    name="MODELS", 
    values=c(GAM = "#FF9999")) +
  theme(legend.position = c(0.8, 0.8)) +
  theme(legend.background=element_rect(fill="white", colour="black"))
```


```{r}
MCDataHourTest <-MCDataHour %>% 
  select(c(time, mu_deltaODwindow, Actinic_photonsm2h, Tube)) %>% 
  filter(Tube == 5) %>% 
   filter(time <= 250) %>% 
     filter(time >= 96) %>% 
  drop_na(mu_deltaODwindow)
  
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(100, 1000000))

MCDataHourTest |>
  ggplot() +
  geom_point(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  geom_line(aes(x = time, y = mu_deltaODwindow, colour = Actinic_photonsm2h)) +
  sc +
  facet_grid(cols = vars(Tube)) +
  theme_bw()
```

#Fitting a GAM model
```{r}
library(mgcv)
gam_model <- gam(mu_deltaODwindow ~ s(time), data = MCDataHourTest)
gam_model$converged
resid_gam <- MCDataHourTest$mu_deltaODwindow - predict(gam_model)
## RMSE
sqrt(mean(resid_gam ^ 2))
```
# Support Vector regression
```{r}
# library(e1071)
# tuned <- tune.svm(mu_deltaODwindow ~ time, MCDataHourTest, kernel = 'radial',
#                   gamma = c(seq(0.1, 1, 0.1), 10^(-6:-1)),
#                   cost = 10^(-3:1))
# tuned

#cost = 10 and gamma = 0.5. these are the best parameters to use with a radial svm kernel in this data.
svr_model <- svm(mu_deltaODwindow ~ time, data = MCDataHourTest, kernel = 'radial',
                 cost = 100, gamma = 50.5)
resid_svr <- MCDataHourTest$mu_deltaODwindow - predict(svr_model)
sqrt(mean(resid_svr ^ 2))
```



```{r}
## test residuals
test_resid_gam <- MCDataHourTest$mu_deltaODwindow - predict(gam_model, MCDataHourTest)
## test RMSE
sqrt(mean(test_resid_gam ^ 2))

## R Squared
cor(MCDataHourTest$mu_deltaODwindow, predict(gam_model, MCDataHourTest)) ^ 2


## test residuals
test_resid_svr <- MCDataHourTest$mu_deltaODwindow - predict(svr_model, MCDataHourTest)
## test RMSE
sqrt(mean(test_resid_svr ^ 2))

## R Squared
cor(MCDataHourTest$mu_deltaODwindow, predict(svr_model, MCDataHourTest)) ^ 2
```

```{r}

# MCDataHourTest$gam_pred <- predict(gam_model, MCDataHourTest)
# 
# ggplot(MCDataHourTest, aes(x = time, y = mu_deltaODwindow)) + 
#   geom_point(alpha = 0.3) + 
#   geom_line(aes(y = gam_pred, 
#             color = 'GAM'), size = 1.3) +
#   scale_colour_manual(
#     name="MODELS", 
#     values=c(GAM = "#FF9999")) +
#   theme(legend.position = c(0.8, 0.8)) 
```

```{r}
MCDataHourTest$svr_pred <- predict(svr_model, MCDataHourTest)


ggplot(MCDataHourTest, aes(x = time, y = mu_deltaODwindow)) + 
  geom_point(alpha = 0.3) + 
  geom_line(aes(y = svr_pred,
            color = 'SVR_radial'), size = 1.3) +
  scale_colour_manual(
    name="MODELS", 
    values=c(GAM = "#FF9999", SVR_radial = "#0072B2")) +
  theme(legend.position = c(0.8, 0.8)) +
  theme(legend.background=element_rect(fill="white", colour="black"))
```



